# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('text', models.CharField(default='', max_length=10000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
