# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doc_type', models.CharField(default=b'', max_length=50)),
                ('doc_mime', models.CharField(default=b'', max_length=50)),
                ('doc_encoded', models.TextField(default=b'')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=500)),
                ('session_name', models.CharField(default=b'', max_length=500)),
                ('special', models.BooleanField()),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.CharField(default=b'', max_length=1)),
                ('party', models.CharField(default=b'', max_length=1)),
                ('role', models.CharField(default=b'', max_length=10)),
                ('name', models.CharField(default=b'', max_length=10)),
                ('first_name', models.CharField(default=b'', max_length=10)),
                ('middle_name', models.CharField(default=b'', max_length=10)),
                ('last_name', models.CharField(default=b'', max_length=10)),
                ('district', models.CharField(default=b'', max_length=10)),
                ('follow_the_money_id', models.CharField(default=b'', max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='text',
        ),
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_action',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_action_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 5, 5, 57, 3, 46126, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='number',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='status_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='billrevision',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bills.Session'),
            preserve_default=False,
        ),
    ]
