# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20160605_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='bills',
            field=models.ManyToManyField(to='bills.Bill'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='committee_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='committee_sponsor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='nickname',
            field=models.CharField(default=b'', max_length=25),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='suffix',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='district',
            field=models.CharField(default=b'', max_length=25),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='first_name',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='last_name',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='middle_name',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
