# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20160605_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='billrevision',
            name='raw_text',
            field=models.TextField(default=b''),
        ),
    ]
