# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='text',
        ),
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_action',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_action_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='number',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='status_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
