# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20160604_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=500)),
                ('session_name', models.CharField(default=b'', max_length=500)),
                ('special', models.BooleanField()),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('state_id', models.IntegerField()),
            ],
        ),
    ]
